insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('DBS', 2012, 'Maroon', 'Aston Martin', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Prius', 2011, 'Red', 'Toyota', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Corolla', 2001, 'Yellow', 'Toyota', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Suburban 2500', 1996, 'Green', 'GMC', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Spectra', 2002, 'Maroon', 'Kia', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Thunderbird', 1967, 'Pink', 'Ford', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Sidekick', 1990, 'Green', 'Suzuki', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('X5', 2004, 'Goldenrod', 'BMW', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Traverse', 2012, 'Mauv', 'Chevrolet', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Corolla', 2011, 'Yellow', 'Toyota', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Silverado 3500', 2007, 'Turquoise', 'Chevrolet', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Villager', 2001, 'Aquamarine', 'Mercury', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Malibu', 2006, 'Maroon', 'Chevrolet', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('RSX', 2006, 'Teal', 'Acura', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Tiburon', 2008, 'Maroon', 'Hyundai', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('5 Series', 1994, 'Pink', 'BMW', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Grand Voyager', 2000, 'Orange', 'Plymouth', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Prius', 2008, 'Maroon', 'Toyota', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('300SL', 1993, 'Maroon', 'Mercedes-Benz', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('S-Class', 2007, 'Teal', 'Mercedes-Benz', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Altima', 2012, 'Maroon', 'Nissan', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Somerset', 1986, 'Fuscia', 'Buick', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Continental', 1990, 'Blue', 'Lincoln', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Galant', 1985, 'Orange', 'Mitsubishi', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Continental GTC', 2007, 'Blue', 'Bentley', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Topaz', 1984, 'Red', 'Mercury', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Continental', 1990, 'Fuscia', 'Lincoln', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Cougar', 2001, 'Turquoise', 'Mercury', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Topaz', 1993, 'Violet', 'Mercury', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('A8', 2012, 'Maroon', 'Audi', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Civic', 1985, 'Green', 'Honda', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('MKX', 2010, 'Puce', 'Lincoln', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Panamera', 2011, 'Fuscia', 'Porsche', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Silhouette', 2002, 'Yellow', 'Oldsmobile', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Explorer Sport Trac', 2000, 'Green', 'Ford', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Sidekick', 1993, 'Green', 'Suzuki', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('430', 1990, 'Teal', 'Maserati', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Cherokee', 2000, 'Purple', 'Jeep', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('CR-V', 1997, 'Mauv', 'Honda', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('E350', 2010, 'Puce', 'Ford', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('6000', 1990, 'Mauv', 'Pontiac', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('LTD', 1984, 'Purple', 'Ford', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Rodeo', 2004, 'Orange', 'Isuzu', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Mariner', 2008, 'Maroon', 'Mercury', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Bonneville', 1968, 'Orange', 'Pontiac', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Golf', 1996, 'Aquamarine', 'Volkswagen', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('RVR', 1995, 'Teal', 'Mitsubishi', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Celica', 2004, 'Fuscia', 'Toyota', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Monterey', 2004, 'Blue', 'Mercury', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Outlander', 2012, 'Goldenrod', 'Mitsubishi', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('5 Series', 1992, 'Teal', 'BMW', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Achieva', 1995, 'Fuscia', 'Oldsmobile', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('3000GT', 1995, 'Turquoise', 'Mitsubishi', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('940', 1994, 'Teal', 'Volvo', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('GTO', 2006, 'Purple', 'Pontiac', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('F-Series Super Duty', 2007, 'Green', 'Ford', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Savana 3500', 2002, 'Fuscia', 'GMC', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('B-Series', 2007, 'Orange', 'Mazda', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('626', 1997, 'Puce', 'Mazda', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Land Cruiser', 1998, 'Blue', 'Toyota', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Rendezvous', 2003, 'Mauv', 'Buick', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('300M', 2003, 'Khaki', 'Chrysler', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Bonneville', 1995, 'Teal', 'Pontiac', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('C70', 2013, 'Puce', 'Volvo', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Prizm', 1993, 'Khaki', 'Geo', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Thunderbird', 1972, 'Indigo', 'Ford', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('LeSabre', 1997, 'Purple', 'Buick', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('F350', 2003, 'Maroon', 'Ford', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Jetta', 2000, 'Khaki', 'Volkswagen', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('C8 Double 12 S', 2006, 'Green', 'Spyker', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Neon', 2000, 'Green', 'Dodge', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('S4', 2002, 'Maroon', 'Audi', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Yukon', 2005, 'Khaki', 'GMC', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('DB9', 2007, 'Maroon', 'Aston Martin', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Dakota Club', 2001, 'Crimson', 'Dodge', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('M6', 2009, 'Mauv', 'BMW', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('C-MAX Hybrid', 2013, 'Teal', 'Ford', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('B-Series', 1993, 'Violet', 'Mazda', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('350Z', 2007, 'Pink', 'Nissan', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Yukon', 2007, 'Teal', 'GMC', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('645', 2004, 'Yellow', 'BMW', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('900', 1993, 'Khaki', 'Saab', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Accord', 2009, 'Aquamarine', 'Honda', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Marquis', 1984, 'Turquoise', 'Mercury', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('M3', 1997, 'Puce', 'BMW', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('3500 Club Coupe', 1996, 'Red', 'GMC', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Envoy', 2000, 'Goldenrod', 'GMC', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Canyon', 2010, 'Khaki', 'GMC', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Escalade EXT', 2007, 'Red', 'Cadillac', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Continental', 2008, 'Purple', 'Bentley', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('LS Hybrid', 2011, 'Crimson', 'Lexus', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Cayenne', 2004, 'Orange', 'Porsche', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('PT Cruiser', 2006, 'Crimson', 'Chrysler', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Tahoe', 2003, 'Red', 'Chevrolet', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('G5', 2008, 'Mauv', 'Pontiac', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Rio', 2006, 'Crimson', 'Kia', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Town & Country', 1998, 'Crimson', 'Chrysler', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('F-Series', 2001, 'Teal', 'Ford', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('CL', 2003, 'Green', 'Acura', 4);
insert into car_table (car_model, car_release_year, car_color, car_company, quantity) values ('Swift', 1987, 'Puce', 'Suzuki', 4);